- name: nodejs setup
  import_role:
    name: common
    tasks_from: nodejs-setup

- name: download and unzipping catalogue artifact
  unarchive:
    src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_sec: yes
- name: npm 
  import_role:
    name: common
    tasks_from: npm-install

- name: copying catalogue service
  copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: daemon-reload
  systemd_service:
    daemon-reload: true

- name: enable and start catalogue
  service:
    name: catalogue
    state: started
    enabled: true

- name: copying mongo.repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb-org-shell
  yum:
    name: mongodb-org-shell
    state: installed

- name: loading schema
  shell: mongo --host 35.173.230.224 </app/schema/catalogue.js
