- name: installing web component
  hosts: web
  become: yes

  tasks:
  - name: installing nginx
    yum:
      name: nginx
      state: installed
  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true
  - name: remove the defalut hmtl file
    file:
      path: /usr/share/nginx/html/*
      state: absent 
  - name: remove the defalut hmtl file
    file:
      path: /usr/share/nginx/html/*
      state: directory
  - name: download and unzip the artifact
    unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /usr/share/nginx/html/
      remote_src: yes
  - name: copying roboshop.conf
    copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 
  - name: restart nginx
    service:
      name: nginx
      state: restarted